"""add_image_url_to_attribute_nodes

Revision ID: 0c92bb86e9cd
Revises: abc5a9a36c5b
Create Date: 2026-01-09 14:05:54.269687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c92bb86e9cd'
down_revision: Union[str, None] = 'abc5a9a36c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_nodes', sa.Column('image_url', sa.String(length=500), nullable=True, comment='Image/logo URL for the entity (used in Relations management)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_nodes', 'image_url')
    # ### end Alembic commands ###
