"""Add page_type field to attribute_nodes

Revision ID: ba0a6a525f3f
Revises: 16781a3b6e95
Create Date: 2025-12-24 22:15:15.954002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba0a6a525f3f"
down_revision: Union[str, None] = "16781a3b6e95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add page_type column with default value
    op.add_column(
        "attribute_nodes",
        sa.Column(
            "page_type",
            sa.String(length=20),
            nullable=False,
            comment="Page type: profile, accessories, glazing",
            server_default="profile",
        ),
    )

    # Update existing records to have page_type='profile' (all current data is profile data)
    op.execute(
        "UPDATE attribute_nodes SET page_type = 'profile' WHERE page_type IS NULL OR page_type = ''"
    )

    # Remove server default after data migration
    op.alter_column("attribute_nodes", "page_type", server_default=None)

    # Create new composite index
    op.create_index(
        "idx_attribute_nodes_mfg_page_node_type",
        "attribute_nodes",
        ["manufacturing_type_id", "page_type", "node_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_attribute_nodes_mfg_page_node_type", table_name="attribute_nodes")
    op.drop_column("attribute_nodes", "page_type")
    # ### end Alembic commands ###
