"""Add display_name field to attribute_nodes

Revision ID: d3e80a73ebc5
Revises: 0c92bb86e9cd
Create Date: 2026-01-13 13:01:17.367600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3e80a73ebc5'
down_revision: Union[str, None] = '0c92bb86e9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attribute_nodes', sa.Column('display_name', sa.String(length=300), nullable=True, comment="Human-readable display name. If null, auto-generated from 'name' field using title case conversion."))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attribute_nodes', 'display_name')
    # ### end Alembic commands ###
